language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - MONO_IOMAP=case xbuild "AWSSDK_DotNet35/AWSSDK_DotNet35.sln" /p:TargetFrameworkProfile="" /p:TargetFrameworkVersion="v3.5" /p:TreatWarningsAsErrors="false"